version: '3.8'

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb_server
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - TZ=America/Mexico_City
    restart: unless-stopped